aws_common: &aws_common
  env:
  - secure: "aiDSqJC0aZp9A+ytR+3EAXO+/uPfMpKLRCA0Gtx8r2O9mpmFd3qeNjxGyhjTSqBQy1jFpTjy0zi1ZtAaYOdrM6OMSFWPGOx9NfWKLKHJ4JP2pY7Mo5wwiGRvFLQfvf//2OzhX765aaGwJSVgBdOyniQPQtmoVvJuEKlGP6aJCyEAZX3W2Vyt286TxUGwaUbomGMJvc/ljHecV+SZb8ANIXFgs/mERaBbpHyKQ1LFBX+I5kzSuB86i9AMcUEEs/ckGc58mxPFgjs6jnXponv4AG58NVp4HN4kEW4Jezch5Qw5DA4B77++vrKFfUEWuE0FYa0nqeo/TSX/wwDg/1SkMDgVny+UwGxPaTM32wKfhuOrpMwzw89+XgK0xO+bB1akFfCXr+TE0/4LxV67KmSpcBR9WPMMAsInBKYP5PEKw3cLrDUL/FMP2ZyGodaGNsseUxuxhtLcWpEEy8a1qHdUZzLmx+CkTN/nvh/e2zq64sC3u7kZaCML53npFtT8gGAk7C61yOwonlGdQlWaRghd+hNURTtY9YqMe8uDfO6zakEDEqdfPBOuaApPPmJQ64PVVuQU1+XLGNneSjaBLzGTyAtQ1f4V0BjfN5aNdHAQAKej0jWw/wTUG9A/8/qsywnPFKM6hwx5Or6klkeqgh4TdIoTFHB+5HWk1iw4vVxvkYk="
  - secure: "Uxw/jspO8/G9EPS22VJfNe/4+V4kAJcwGEAz0oN9I3oXMaV3wi/FH6zHnQFZcqcHM4oyXI+0VQskxUMtZ10M3GBvvY87AFSDz9cChlJtvSQ8JbL0gnGDO0N9w4s6TVpaA4qcFqFh3HtoZ5G3Dakqg/yumXaHDGmmihMvUnSEVb3EG4ZW4MAtpzOiVezpmLCN9NmnXcfB07VwpJrn9uJqpNG9Tv5kVXFtg4L1faI9gq021w8BawTYE/vaM1zxAtDE+8emE58P4lzPngxdByJwA0JU/3OauT7565wpLlUTAE20WB9OLPKg/PWLpTvbEwPcQJkeNpYaSlXioi8zgcCoyeSWcxGpEwiixRikO9SmsA/89XVSZd/jaO6RdUv3kK2/wFcAwM//f4k0NYJq3hr88eaX3tXgWz/xpsH1Ny8OHCPJIyt3H1riyYf6PYigUjj/ClFJ7RZLc6kylxoDRX1JCLud6jl6KdaaxCWrGuYRFC8W67m1naxQ+UeRnogf8dMU6ROowpFmwKu10oWl9reL39APxAGldZtQcwW+SyHYi7Wb+bf/eRZI5wnatNDyqm/W39Ark5wOcGlWSTMftFY2TJiyZaBF+arH5QJ/D8kZ8JCoYgVyMez+xVldlEclC5qAhFMBdu/gfzSavZY90oO+IdIRA47X/BZ6cN4z/FgRw3U="
  - AWS_DEFAULT_REGION=eu-west-1
  - PATH=$HOME/.local/bin:$PATH
  before_install:
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://dd-cicd/master/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
dd_common: &dd_common
  if: type IN (push)
  sudo: required
  dist: trusty
  language: bash
  install:
  - sudo apt-get -y install dpkg-repack tree build-essential apt-rdepends
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g yarn
jobs:
  include:
    # =======================
    # Code quality scans (start)
    # =======================
    - stage: Code quality, unit tests, e2e tests
      if: type IN (push)
      dist: trusty
      language: bash
      addons:
        sonarcloud:
          organization: "thailekha-github"
          token:
            secure: "RO7rfVtdRTOOIRe88Q3TIcVL2eO1kgR7NYofjNFOoWGgYsfi8yEA84C4t0qy2e6RBD6z3k2F5+aKpPf65lrIGCXeEG4ar/bHlHbUSQtkGQ1vn9xqUePfdahjtOog9LY3/22bMG8mEmJbjgW0FxIq1fVZvwjrf1uCMIJg0EPr4u7ngQO/nGqtVm/lAdtMA68MrW1um8QIYUUHmEBzr3jltBIx/ybCVV1zIfi/f2dGFYd5cl47AOlT297pWhnhZyoy6gfrUivWV/tNMpT4feB4FttnP9ZsGTqMLbx/6tnJRUIV+ep/bkg/FtBTkpGFOxHvfwuuA6q7fZa4X3URtih1RR95oAfKZQwGFuNc7y9nK58ySGqVJ3iCdfNAKOqVqDSTm2n3qilcBVgNecjpFpeCJw8sKcp1jSy4LWepdWUITnhinxeFY/gz8tZnGUYIPpMUmz9doQehp+CIR6lQQ5Jn5oARuG3O7v8oCBcgZCh2uKqiXInKDqVaOu3sZl6ZS/YxiYC+MbARmGPyArvahOgb+hVUBwKU6vXFBcSqY1MMmL205Z3EUzJMdUqY7wptOtsFV9k/ttwxTvUHw0W7E21opp5pnacgUnTPDckDjICu8YSYF7boduALDt7bm9oDBOQ+FUt9aI2pBOCZ895iByqeNgvCmVDq62G5SCcrappVzxg="
      script:
      - sonar-scanner --debug
    # =======================
    # Code quality scans (end)
    # =======================
    # =======================
    # Unit tests (start)
    # =======================
    -
      <<: *dd_common
      before_script:
      - yarn install
      - npm run build
      script:
      - npm run test
    # =======================
    # Unit tests (end)
    # =======================
    # =======================
    # E2E tests (start)
    # =======================
    -
      <<: *aws_common
      <<: *dd_common
      before_script:
      - yarn install
      - npm run build
      script:
      - sudo ./node_modules/.bin/nyc --reporter=json --reporter=lcov --reporter=text ./node_modules/.bin/_mocha ./dist/tests/ec2.test.js --grep foo --timeout 20000 --exit
      - sudo mv coverage/coverage-final.json ~/$TRAVIS_BUILD_NUMBER/coverage-ec2.json
      - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://dd-cicd/master/$TRAVIS_BUILD_NUMBER
    # =======================
    # E2E tests (end)
    # =======================
    # =======================
    # Code coverage (start)
    # =======================
    - stage: Aggregate coverage
      if: NOT branch = master
      <<: *aws_common
      sudo: false
      language: node_js
      node_js: "8"
      install:
      - npm i -g codecov istanbul-combine
      script:
      - istanbul-combine -d coverage -p summary -r text -r lcov ~/$TRAVIS_BUILD_NUMBER/coverage-ec2.json
      - ls coverage
      - cp coverage/lcov.info coverage.lcov
      - cp coverage/lcov.info ~/$TRAVIS_BUILD_NUMBER/lcov.info
      - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://dd-cicd/master/$TRAVIS_BUILD_NUMBER
      - mkdir secrets
      - openssl aes-256-cbc -K $encrypted_f2a8f85a9385_key -iv $encrypted_f2a8f85a9385_iv -in assets/id_rsa.enc -out secrets/id_rsa -d
      - eval "$(ssh-agent -s)"
      - chmod 600 secrets/id_rsa
      - ssh-add secrets/id_rsa
      - git config --global user.email "thailekha@yahoo.com"
      - git config --global user.name "Travis"
      - git remote add origin-ssh git@github.com:thailekha/dynamic-dockerizer-master.git
      - git fetch origin-ssh
      - git checkout $TRAVIS_BRANCH
      - git add coverage/lcov.info
      - git commit -m "[ci skip] code coverage"
      - git push origin-ssh $TRAVIS_BRANCH -f
    # =======================
    # Code coverage (end)
    # =======================